CC     = gcc
SRCS   = $(wildcard src/*.c)
OBJS   = $(SRCS:src/%.c=bin/%.o)
TARGET = bin/hopital

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

bin/%.o: src/%.c
	$(CC) -c $< -I include -o $@

clean:
	del bin\*.o bin\hopital.exe